name: 'Modules Validation'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-modules:
    name: Validate Module
    runs-on: ubuntu-latest
    # Definiujemy listę Twoich folderów
    strategy:
      matrix:
        module: [s3_bucket, vpc]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Format Check
        # Sprawdza czy kod jest ładnie sformatowany (terraform fmt)
        working-directory: ./modules/${{ matrix.module }}
        run: terraform fmt -check

      - name: Terraform Init
        # Inicjalizacja bez backendu (tylko do sprawdzenia składni)
        working-directory: ./modules/${{ matrix.module }}}
        run: terraform init -backend=false

      - name: Terraform Validate
        # Główny test - sprawdza czy kod jest poprawny technicznie
        working-directory: ./modules/${{ matrix.module }}
        run: terraform validate
