name: 'Modules Validation'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-modules:
    name: Validate Module
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Tutaj wpisujesz pełne ścieżki do folderów, w których masz pliki .tf
        module-path: 
          - "Network/modules/vpc"
          - "S3_bucket/modules/s3_bucket" # dopasuj tę ścieżkę do faktycznej lokalizacji S3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        # Teraz używamy pełnej ścieżki z macierzy
        working-directory: ./${{ matrix.module-path }}
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: ./${{ matrix.module-path }}
        run: terraform validate
